import { FALLBACK_ROWS } from '../fallbackRows';

// Fallback Mock Snapshot Data
export const FALLBACK_SNAPSHOT = {
  overviewKpis: {
    totalInteractions: 8155,
    totalTelemetry: 2578,
    totalTokens: 35700000,
    toolCallsCount: 1813,
    activeConnectors: 17,
  },
  dailyActivity: [
    { date: '08-01', count: 184 },
    { date: '08-02', count: 92 },
    { date: '08-03', count: 215 },
    { date: '08-04', count: 480 },
    { date: '08-05', count: 730 },
    { date: '08-06', count: 1120 },
    { date: '08-07', count: 960 },
    { date: '08-08', count: 1450 },
    { date: '08-09', count: 1220 },
    { date: '08-10', count: 1680 },
  ],
  agentPopularity: [
    { name: 'Cosmere Data Agent', value: 3553 },
    { name: 'Entraid-Test Agent', value: 1928 },
    { name: 'Sharepoint Search', value: 987 },
    { name: 'Hidden GE 2', value: 634 },
    { name: 'Support Router', value: 489 },
    { name: 'Ingestion Search', value: 316 },
  ],
  genaiTelemetryTokens: [
    { agent: 'Cosmere Agent', inputTokens: 14200000, outputTokens: 3100000 },
    { agent: 'Entraid Test', inputTokens: 8900000, outputTokens: 1450000 },
    { agent: 'Sharepoint Agent', inputTokens: 5200000, outputTokens: 980000 },
    { agent: 'Support Router', inputTokens: 2100000, outputTokens: 420000 },
    { agent: 'Search Connector', inputTokens: 950000, outputTokens: 190000 },
  ],
  toolInvocations: [
    { tool: 'sharepoint_agent__search_tool', count: 987 },
    { tool: 'ingestion_search_agent', count: 316 },
    { tool: 'cosmere', count: 256 },
    { tool: 'google_search_tool', count: 142 },
    { tool: 'jira__search_issues', count: 46 },
    { tool: 'google_drive_agent__search_drive_tool', count: 34 },
    { tool: 'email_agent__search_email_tool', count: 12 },
  ],
  connectorUsageAll: [
    {
      connector_name: 'Sharepoint',
      connector_type: 'Agent Tool',
      usage_count: '987',
      tools_used: 'sharepoint_agent__search_tool',
      user_email: 'qos-test-user@example.com',
      first_used_at: '2026-08-10 13:24:58',
      last_used_at: '2026-08-13 13:04:44',
    },
    {
      connector_name: 'Ingestion Search',
      connector_type: 'Agent Tool',
      usage_count: '316',
      tools_used: 'ingestion_search_agent__ingestion_search_tool',
      user_email: 'qos-test-user@example.com',
      first_used_at: '2026-08-10 00:00:31',
      last_used_at: '2026-08-19 15:26:07',
    },
    {
      connector_name: 'Cosmere',
      connector_type: 'Search Data Source',
      usage_count: '259',
      tools_used: 'cosmere',
      user_email: 'admin@example.com',
      first_used_at: '2026-08-10 13:07:12',
      last_used_at: '2026-09-09 16:04:53',
    },
    {
      connector_name: 'Google Search',
      connector_type: 'Agent Tool',
      usage_count: '9',
      tools_used: 'google_search_tool',
      user_email: 'admin@example.com',
      first_used_at: '2026-08-10 13:07:43',
      last_used_at: '2026-08-27 15:23:09',
    },
    {
      connector_name: 'Email',
      connector_type: 'Agent Tool',
      usage_count: '4',
      tools_used: 'email_agent__search_email_tool',
      user_email: 'admin@example.com',
      first_used_at: '2026-08-13 16:26:37',
      last_used_at: '2026-08-19 15:26:02',
    },
    {
      connector_name: 'Google Drive',
      connector_type: 'Agent Tool',
      usage_count: '3',
      tools_used: 'google_drive_agent__search_drive_tool',
      user_email: 'admin@example.com',
      first_used_at: '2026-08-17 11:34:50',
      last_used_at: '2026-08-19 15:26:02',
    },
    {
      connector_name: 'Jira',
      connector_type: 'Agent Tool',
      usage_count: '2',
      tools_used: 'jira__search_issues',
      user_email: 'admin@example.com',
      first_used_at: '2026-08-13 16:26:37',
      last_used_at: '2026-08-17 11:35:03',
    },
  ],
  connectorUsage30d: [
    { connector: 'Sharepoint', calls: 987, users: 4 },
    { connector: 'Ingestion Search', calls: 316, users: 3 },
    { connector: 'Cosmere Search', calls: 256, users: 2 },
    { connector: 'Google Search', calls: 9, users: 1 },
    { connector: 'Email', calls: 4, users: 1 },
    { connector: 'Google Drive', calls: 3, users: 1 },
    { connector: 'Jira', calls: 2, users: 1 },
  ],
  topConnectorUsers: [
    { user: 'qos-test-user@example.com', calls: 745 },
    { user: 'admin@example.com', calls: 396 },
    {
      user: '123456789012-compute@developer.gserviceaccount.com',
      calls: 120,
    },
    { user: 'alex.morgan@example.com', calls: 94 },
  ],
  aiFinishReasons: [
    { name: 'STOP', value: 8940 },
    { name: 'FINISH_UNSPECIFIED', value: 1890 },
    { name: 'MAX_TOKENS', value: 124 },
    { name: 'SAFETY', value: 28 },
    { name: 'UNEXPECTED_TOOL_CALL', value: 3 },
  ],
  agentFeedback: [
    { agent: 'Enterprise Data Agent', thumbsUp: 1, thumbsDown: 1, total: 2 },
    { agent: 'Sharepoint Agent', thumbsUp: 12, thumbsDown: 2, total: 14 },
    { agent: 'Core Assistant', thumbsUp: 28, thumbsDown: 4, total: 32 },
    { agent: 'Calendar Agent', thumbsUp: 5, thumbsDown: 0, total: 5 },
  ],
  rows: FALLBACK_ROWS,
};
